name: Generate Podcast Feeds

on:
  push:
    branches:
      - main  # only trigger when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    # Prevent recursion (don’t run again on commits made by the bot)
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Add all modified files
          git add .

          # Commit only if there are changes
          git diff --cached --quiet || git commit -m "Modified Feed"

          # Push using GitHub token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
